-- Table: public.Sales

-- DROP TABLE IF EXISTS public."Sales";

CREATE TABLE IF NOT EXISTS public."Sales"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "SaleNumber" text COLLATE pg_catalog."default" NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL,
    "Customer" text COLLATE pg_catalog."default" NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Branch" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Sales"
    OWNER to developer;
	
	
-- Table: public.Products

-- DROP TABLE IF EXISTS public."Products";

CREATE TABLE IF NOT EXISTS public."Products"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "IsAvailable" boolean NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Products"
    OWNER to developer;


-- Table: public.SaleItems

-- DROP TABLE IF EXISTS public."SaleItems";

CREATE TABLE IF NOT EXISTS public."SaleItems"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "Total" numeric NOT NULL,
    "SaleId" integer,
    CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId")
        REFERENCES public."Sales" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."SaleItems"
    OWNER to developer;
-- Index: IX_SaleItems_SaleId

-- DROP INDEX IF EXISTS public."IX_SaleItems_SaleId";

CREATE INDEX IF NOT EXISTS "IX_SaleItems_SaleId"
    ON public."SaleItems" USING btree
    ("SaleId" ASC NULLS LAST)
    TABLESPACE pg_default;

	
	
-- Table: public.Users

-- DROP TABLE IF EXISTS public."Users";

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Username" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Phone" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Status" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Users"
    OWNER to developer;	